builders:
  super_annotations:
    import: "package:super_annotations/builder.dart"
    builder_factories: [ "buildSuperGeneration" ]
    build_extensions: { ".dart": [ ".g.dart" ] }
    auto_apply: dependents
    build_to: source